"use client";

import Head from "next/head";
import Header from "../components/Header";
import TopCards from "@/components/TopCards";
import RecentOrders from "@/components/RecentOrders";
import PieChart from "@/components/PieChart";

export default function Home() {
  return (
    <>
      <Head>
        <title>Expense Tracker</title>
        <meta name="description" content="generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <main className="bg-gray-100 min-h-screen dark:text-black">
        <Header></Header>
        <TopCards></TopCards>
        <div className="p-4 grid md:grid-cols-3 grid-cols-1 gap-4">
          <RecentOrders></RecentOrders>
          <PieChart></PieChart>
        </div>
      </main>
    </>
  );
}
